# Generated by Django 2.2.12 on 2020-06-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzle_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='flag',
            field=models.CharField(choices=[['new', 'new'], ['needs_constraints', 'needs_constraints'], ['no_puzzle', 'no_puzzle'], ['valid', 'valid'], ['bad_id', 'bad_id'], ['needs_id', 'needs_id'], ['not_sudoku', 'not_sudoku'], ['external_ctc', 'external_ctc']], default='new', max_length=16),
        ),
    ]
