# Generated by Django 2.2.12 on 2020-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
