# Generated by Django 2.2.12 on 2020-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_auto_20200605_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
