# Generated by Django 2.2.12 on 2020-06-16 12:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_auto_20200605_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='flag',
            field=models.CharField(choices=[['new', 'new'], ['no_rules', 'no_rules'], ['valid', 'valid'], ['bad_id', 'bad_id'], ['not_sudoku', 'not_sudoku'], ['external_ctc', 'external_ctc'], ['not_9x9', 'not_9x9'], ['bad_render', 'bad_render'], ['vanilla', 'vanilla'], ['maybe_not_9x9', 'maybe_not_9x9']], default='new', max_length=16),
        ),
    ]
